### ISSUE TITLE
How to build for Android with node.js native node modules 

### ISSUE THREAD

**Issue by sce9sc** [hampoelz/Capacitor-NodeJS#3]
Great work , nice to see someone interested in embedding node.js .

I am trying to build an android app using capacitor and node.js. I wanted to include other packages inside node.js but it did not seem to work .  Can you please help me. 

Node.js without any modules is working fine, but when I install node modules that use native modules it doesn't 

Thank you in advance.

**Comment by sce9sc** [comment]
The problem seems to be with some native modules like sodium-native. 

I will investigate further. I tried to install it in termux and i had problems there as well .

**Comment by hampoelz** [comment]
To use a native module, it must support the Android platform. For now, you could use the [`sodium-native-nodejs-mobile`](https://github.com/staltz/sodium-native-nodejs-mobile) fork for the android/ios part instead, until mobile platforms are officially supported. If you use the electron integration, you would have to import `sodium-native-nodejs-mobile` or `sodium-native` depending on the platform, since this fork only supports Android and iOS.
