### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by lucaengelhard** [hampoelz/Capacitor-NodeJS#7]
Hey I love this project, but i have problems with getting nodejs to run on my phone. Even though I'm fairly certain that I followed the setup steps exactly, I could still be overlooking something. 

Do you have an example project with the minimum required files to get a basic functionality going? That would be great!

Thanks for the great work!

**Comment by hampoelz** [comment]
Not yet, but you are right, a minimal example would be helpful to get started with this plugin. I will add some example projects in the following weeks.

**Comment by jrobeson** [comment]
@lucaengelhard what problem did you actually have though?

I just added this line https://github.com/hampoelz/Capacitor-NodeJS/blob/main/assets/builtin_modules/bridge/main.js#L3 ) and the import of the appChannel to a basic node project and it worked.

I did have problem with cross compiling native dependencies for a much larger project, but i did eventually figure that part out.

**Comment by lucaengelhard** [comment]
My problem was that after just creating a basic file structure and wanting to test out the functionality, it seemed like there was no connection to the nodejs backend. 

What exactly does your code change/fix?

**Comment by jrobeson** [comment]
There's the side that you use with capacitor (and perhaps ionic) where you

have something like

```js
await NodeJS.addListener('msg-from-nodejs', cb);
await NodeJS.whenReady();
```

The thing about `whenReady` though, is that starts what seems to be a permanent timer (I'm no java expert) to wait to `isNodeEngineReady` to equal  `true`.  It will never equal true UNTIL it gets a messages over the `APP_CHANNEL` of ready. That's what that line does.

As per https://github.com/hampoelz/Capacitor-NodeJS/blob/main/android/src/main/java/net/hampoelz/capacitor/nodejs/NodeJS.java#L115

**Comment by hampoelz** [comment]
> I just added this line https://github.com/hampoelz/Capacitor-NodeJS/blob/main/assets/builtin_modules/bridge/main.js#L3 ) and the import of the appChannel to a basic node project and it worked.

@jrobeson Yeah, it is required that the `appChannel` sends the `ready` command so the implementation knows that the NodeJS part is completely started. However, this should all happen automatically once the bridge module is loaded. _(the code you referenced is actually a part of the bridge module)_.

> The thing about `whenReady` though, is that starts what seems to be a permanent timer (I'm no java expert) in the capacitor plugin code to wait for `isNodeEngineReady` to equal `true`. It will never equal true UNTIL it gets a message over the `APP_CHANNEL` of ready. That's what that line does. That line goes in your nodejs application code.

This is also correct. Since the NodeJS part needs more time to start on some devices than the CapacitorJS part _(see issue #4)_, there is the `whenReady` method. Thereby an interval is executed, which checks if the NodeJS part is started and then resolves the method. So the bridge module has to be loaded for this to work.

In general, the communication between NodeJS and CapacitorJS is "blocked" until the `ready` command is received from the NodeJS part. I didn't mention anywhere in the documentation that the bridge module is that important for communication to work, I should add that.

> My problem was that after just creating a basic file structure and wanting to test out the functionality, it seemed like there was no connection to the nodejs backend.

@lucaengelhard Hmm so did I understand correctly, you imported the bridge module, waited for the nodejs part to be ready loaded and it still doesn't work? Could you check if the `whenReady` method resolves and if there are error messages?

Anyway, on Monday is my last exam for now, after that I will add the sample projects.

**Comment by hampoelz** [comment]
Two example projects are now available. One without additional framework, which is located in the branch [`example/vanilla`](https://github.com/hampoelz/Capacitor-NodeJS/tree/example/vanilla). And a second one, which uses the vitejs framework, is located in [`example/vite`](https://github.com/hampoelz/Capacitor-NodeJS/tree/example/vite).

**Comment by hampoelz** [comment]
The examples currently still use CapacitorJS v4, but in a short test the plugin also worked with v5. After I migrate the plugin to v5 I will also update the example projects.

**Comment by hampoelz** [comment]
@lucaengelhard In fact, I found a bug that prevented the bridge module from loading (see issue #12). With v1.0.0-beta.4 it should be fixed now.
